In [1]:
from siphon.simplewebservice.ndbc import NDBC
import pandas as pd

Get Marine Data from API

In [2]:
df_marine = NDBC.realtime_observations('51101')

Check first rows

In [3]:
df_marine.head()

,wind_direction,wind_speed,wind_gust,wave_height,dominant_wave_period,average_wave_period,dominant_wave_direction,pressure,air_temperature,water_temperature,dewpoint,visibility,3hr_pressure_tendency,water_level_above_mean,time
0,120.0,3.0,5.0,NaN,NaN,NaN,NaN,1017.0,22.3,24.4,NaN,NaN,NaN,NaN,2024-05-21 13:40:00+00:00
1,110.0,2.0,4.0,NaN,NaN,NaN,NaN,1017.0,22.4,24.4,NaN,NaN,NaN,NaN,2024-05-21 13:30:00+00:00
2,100.0,2.0,4.0,1.8,15.0,7.3,185.0,1017.0,22.5,24.5,NaN,NaN,NaN,NaN,2024-05-21 13:20:00+00:00
3,90.0,1.0,3.0,1.8,NaN,7.3,185.0,1016.9,22.4,24.4,NaN,NaN,NaN,NaN,2024-05-21 13:10:00+00:00
4,90.0,1.0,2.0,NaN,NaN,NaN,NaN,1017.0,22.3,24.5,NaN,NaN,-1.4,NaN,2024-05-21 13:00:00+00:00

Rename Columns + Delete Useless Ones

In [4]:
df_marine.rename(columns={'wind_direction': 'Wind Dir (°)', 'wind_speed':'Wind Speed (ms)',
                          'wind_gust':'Wind Gusts 1h (ms)','wave_height':'Wave Height (m)','dominant_wave_period':'Dominant Wave Period (s)',
                          'average_wave_period':'Avg Wave Period (s)', 'dominant_wave_direction': 'Dominant Wave Direction',
                          'air_temperature':'Air Temperature','water_temperature':'Water Temperature','time': 'Datetime','pressure':'Pressure'}, inplace=True)


df_marine = df_marine.drop(columns={'dewpoint', 'visibility','3hr_pressure_tendency','water_level_above_mean'})

Check Head again

In [5]:
df_marine.head(5)

,Wind Dir (°),Wind Speed (ms),Wind Gusts 1h (ms),Wave Height (m),Dominant Wave Period (s),Avg Wave Period (s),Dominant Wave Direction,Pressure,Air Temperature,Water Temperature,Datetime
0,120.0,3.0,5.0,NaN,NaN,NaN,NaN,1017.0,22.3,24.4,2024-05-21 13:40:00+00:00
1,110.0,2.0,4.0,NaN,NaN,NaN,NaN,1017.0,22.4,24.4,2024-05-21 13:30:00+00:00
2,100.0,2.0,4.0,1.8,15.0,7.3,185.0,1017.0,22.5,24.5,2024-05-21 13:20:00+00:00
3,90.0,1.0,3.0,1.8,NaN,7.3,185.0,1016.9,22.4,24.4,2024-05-21 13:10:00+00:00
4,90.0,1.0,2.0,NaN,NaN,NaN,NaN,1017.0,22.3,24.5,2024-05-21 13:00:00+00:00

Check Nombres valeurs vides / Nombre total de lignes

In [6]:
print(df_marine.isnull().sum(),df_marine.shape)

Wind Dir (°)                  13
Wind Speed (ms)                7
Wind Gusts 1h (ms)             7
Wave Height (m)             3003
Dominant Wave Period (s)    4346
Avg Wave Period (s)         3006
Dominant Wave Direction     3006
Pressure                       6
Air Temperature                7
Water Temperature             47
Datetime                       0
dtype: int64 (6502, 11)

Check Data Types

In [7]:
df_marine.dtypes

Wind Dir (°)                            float64
Wind Speed (ms)                         float64
Wind Gusts 1h (ms)                      float64
Wave Height (m)                         float64
Dominant Wave Period (s)                float64
Avg Wave Period (s)                     float64
Dominant Wave Direction                 float64
Pressure                                float64
Air Temperature                         float64
Water Temperature                       float64
Datetime                    datetime64[ns, UTC]
dtype: object

Delete Rows With Empty Values in Data Columns

In [8]:
# Spécifier les colonnes à considérer pour la suppression des lignes
columns_to_check = ['Wind Dir (°)', 'Wind Speed (ms)', 'Wind Gusts 1h (ms)', 'Wave Height (m)', 'Dominant Wave Period (s)', 
                    'Avg Wave Period (s)', 'Dominant Wave Direction', 'Pressure', 'Air Temperature', 'Water Temperature']

# Supprimer les lignes avec des valeurs nulles dans les colonnes spécifiées
df_marine.dropna(subset=columns_to_check, inplace=True)

# Afficher le DataFrame après la suppression des lignes
df_marine.isnull().sum()

Wind Dir (°)                0
Wind Speed (ms)             0
Wind Gusts 1h (ms)          0
Wave Height (m)             0
Dominant Wave Period (s)    0
Avg Wave Period (s)         0
Dominant Wave Direction     0
Pressure                    0
Air Temperature             0
Water Temperature           0
Datetime                    0
dtype: int64

In [9]:
df_marine.head()

,Wind Dir (°),Wind Speed (ms),Wind Gusts 1h (ms),Wave Height (m),Dominant Wave Period (s),Avg Wave Period (s),Dominant Wave Direction,Pressure,Air Temperature,Water Temperature,Datetime
2,100.0,2.0,4.0,1.8,15.0,7.3,185.0,1017.0,22.5,24.5,2024-05-21 13:20:00+00:00
5,100.0,2.0,3.0,1.6,8.0,7.0,105.0,1017.0,22.3,24.5,2024-05-21 12:50:00+00:00
8,90.0,2.0,3.0,1.6,8.0,7.0,111.0,1017.2,22.3,24.4,2024-05-21 12:20:00+00:00
11,120.0,2.0,4.0,1.6,15.0,7.4,185.0,1017.4,22.4,24.5,2024-05-21 11:50:00+00:00
14,130.0,4.0,5.0,1.6,15.0,7.4,196.0,1017.7,22.7,24.4,2024-05-21 11:20:00+00:00

In [10]:
df_marine_final= df_marine
df_marine_final.to_csv('df_marine_final.csv', index=False)